### ISSUE TITLE
Suggestion for a Print Layout 

### ISSUE THREAD

**Issue by jeyemwey** [cooklang/CookCLI#65]
Hi, thank you for making Cooklang!

I have created some CSS adjustments for the Recipe page which makes it easier to print the page.

Since I don't know anything about Stelve or Swift, I cannot make a real PR, but I feel like it would be a waste to not share it. So if you ever want to incorporate something like this, I invite you to take this as an example.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/2796271/179369753-a3fab6d3-d4af-4faa-9ba0-8a7d988d7880.png">

And that is the code behind it:

```css
@media print {
    nav.navbar, .btn {
        display: none;
    }

    ol.breadcrumb li:not(:last-of-type) {
        display: none;
    }

    li.breadcrumb-item {
        font-size: 2em;
    }

    .breadcrumb-item+.breadcrumb-item::before {
        content: '';
    }
    

    ul.nav {
        display: none;
    }


    .tab-content>.tab-pane {
        display: block;
    }

    .tab-content>.tab-pane:first-of-type {
        width: 20rem;
        border: 1px solid black;
        border-radius: 0px;
        padding: 1.5rem 1rem;

        float: left;
        margin-right: 2rem;
        margin-left: 1rem;
    }

    .tab-content>.tab-pane:nth-of-type(2) {
        display: none;
    }
}
```
